export const GET_RESULT_SEARCH_USER = 'GET_RESULT_SEARCH_USER';
export const SET_RESULT_SEARCH_USER = 'SET_RESULT_SEARCH_USER';
export const SET_SEARCH_USER_HISTORY = 'SET_SEARCH_USER_HISTORY';

export const GET_REPOS = 'GET_REPOS';
export const SET_REPOS = 'SET_REPOS';

export const SET_LOADER = 'SET_LOADER';
