export const GET_RESULT_SEARCH_USER = 'GET_RESULT_SEARCH_USER';
export const SET_RESULT_SEARCH_USER = 'SET_RESULT_SEARCH_USER';

export const GET_REPOS = 'GET_REPOS';
export const SET_REPOS = 'SET_REPOS';
